"""
AgentState and Pydantic models for the 2108Trade AI pipeline.

All models follow the architecture doc (v1.0.0-draft).
Every model uses Pydantic for strict validation — no black-box data.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Annotated, Any, Literal, Optional, TypedDict

from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field


# ── Enums ───────────────────────────────────────────────────────────────

class Sentiment(str, Enum):
    BULLISH = "bullish"
    BEARISH = "bearish"
    NEUTRAL = "neutral"


class TradeAction(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class PipelineStatus(str, Enum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ABORTED = "aborted"
    ERROR = "error"


class DataFreshness(str, Enum):
    REAL_TIME = "real_time"
    RECENT = "recent"
    STALE = "stale"
    UNKNOWN = "unknown"


# ── Core Data Models ────────────────────────────────────────────────────

class Citation(BaseModel):
    """A citable data source used in analysis."""
    source: str = Field(..., description="Data source name (e.g., 'Yahoo Finance', 'SEC EDGAR')")
    timestamp: datetime = Field(..., description="When the data was fetched")
    url: Optional[str] = Field(None, description="Optional link to the source")
    metric: Optional[str] = Field(None, description="Specific metric cited (e.g., 'P/E ratio: 24.3')")


class MarketAssessment(BaseModel):
    """Output of the Market Analysis Agent."""
    sentiment: Sentiment = Field(..., description="Overall market sentiment for the symbols")
    key_findings: list[str] = Field(default_factory=list, description="Key observations with data backing")
    citations: list[Citation] = Field(default_factory=list, description="Data sources used")
    risk_factors: list[str] = Field(default_factory=list, description="Identified risk factors")
    data_freshness: DataFreshness = Field(DataFreshness.UNKNOWN, description="How fresh the input data is")
    confidence: float = Field(ge=0.0, le=1.0, default=0.5, description="Confidence score for the assessment")
    market_open: bool = Field(default=True, description="Whether the target market is currently open")


class TradeCandidate(BaseModel):
    """A potential trade generated by the Strategy Agent."""
    symbol: str = Field(..., description="Ticker symbol")
    action: TradeAction = Field(..., description="Buy, sell, or hold")
    rationale: str = Field(..., description="Why this trade is recommended")
    confidence: float = Field(ge=0.0, le=1.0, description="Model confidence in this candidate")
    supporting_evidence: list[str] = Field(default_factory=list, description="Data points backing the recommendation")
    time_horizon: str = Field("short_term", description="Expected holding period (e.g., 'short_term', 'medium_term', 'long_term')")


class ApprovedCandidate(BaseModel):
    """A trade candidate that passed risk validation."""
    candidate: TradeCandidate = Field(..., description="The original trade candidate")
    risk_score: float = Field(ge=0.0, le=1.0, description="Risk score (lower is safer)")


class RejectedCandidate(BaseModel):
    """A trade candidate that was rejected by the Risk Agent."""
    candidate: TradeCandidate = Field(..., description="The original trade candidate")
    reason: str = Field(..., description="Why the candidate was rejected")


class RiskValidationReport(BaseModel):
    """Output of the Risk Agent."""
    approved: list[ApprovedCandidate] = Field(default_factory=list)
    rejected: list[RejectedCandidate] = Field(default_factory=list)


class TradeRecommendation(BaseModel):
    """Final output of the Explanation Agent — the full analysis result."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    candidates: list[ApprovedCandidate] = Field(default_factory=list)
    reasoning_chain: str = Field("", description="Full plain-language reasoning chain")
    citations: list[Citation] = Field(default_factory=list)
    risk_summary: str = Field("", description="Summary of risk assessment")
    disclaimer: str = Field(
        "This is an AI-generated analysis for informational purposes only. "
        "It does not constitute financial advice. Past performance does not guarantee future results. "
        "All trading involves risk. Consult a qualified financial advisor before making investment decisions."
    )
    confidence: float = Field(ge=0.0, le=1.0, default=0.0)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    status: PipelineStatus = Field(PipelineStatus.COMPLETED)


# ── Request / Response Models ───────────────────────────────────────────

class AnalyzeRequest(BaseModel):
    """Request to run the full AI pipeline."""
    symbols: list[str] = Field(..., min_length=1, description="Ticker symbols to analyze")
    timeframe: str = Field("1d", description="Analysis timeframe (e.g., '1d', '1w', '1m')")
    data_sources: list[str] = Field(default_factory=lambda: ["market_data"], description="Data sources to use")
    user_profile: Optional[dict[str, Any]] = Field(None, description="Optional user risk/profile overrides")


class AnalyzeResponse(BaseModel):
    """Response from the AI pipeline."""
    analysis_id: str
    recommendation: TradeRecommendation
    processing_time_ms: float
    model_used: str


class FeedbackRequest(BaseModel):
    """User feedback on a trade recommendation."""
    analysis_id: str = Field(..., description="The analysis this feedback refers to")
    rating: Optional[int] = Field(None, ge=1, le=5, description="1-5 star rating")
    helpful: Optional[bool] = Field(None, description="Was the explanation helpful?")
    comments: Optional[str] = Field(None, description="Free-text feedback")


class HealthResponse(BaseModel):
    """Service health status."""
    status: Literal["healthy", "degraded", "unhealthy"]
    version: str
    ollama_available: bool
    ollama_models: list[str] = Field(default_factory=list)
    model_loaded: Optional[str] = None


class ModelInfo(BaseModel):
    """Information about an available Ollama model."""
    name: str
    size: Optional[str] = None
    modified_at: Optional[str] = None


# ── LangGraph AgentState ────────────────────────────────────────────────

class AgentState(TypedDict, total=False):
    """
    Shared state passed between LangGraph nodes.

    Messages use LangGraph's add_messages reducer so agent nodes can
    append to the message history without mutating state.
    """
    # Request inputs
    symbols: list[str]
    timeframe: str
    data_sources: list[str]
    user_profile: dict[str, Any]

    # Pipeline outputs (populated by each agent in sequence)
    market_assessment: Optional[MarketAssessment]
    candidates: list[TradeCandidate]
    risk_report: Optional[RiskValidationReport]
    recommendation: Optional[TradeRecommendation]

    # Control
    status: PipelineStatus
    error: Optional[str]
    abort_reason: Optional[str]

    # Message history (add_messages reducer)
    messages: Annotated[list[Any], add_messages]
